// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.34.2

package com.example.grpc.auth;

@com.google.protobuf.Generated
public interface AuthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.auth.AuthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string access_token = 1;</code>
   * @return The accessToken.
   */
  java.lang.String getAccessToken();
  /**
   * <code>string access_token = 1;</code>
   * @return The bytes for accessToken.
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <code>string refresh_token = 2;</code>
   * @return The refreshToken.
   */
  java.lang.String getRefreshToken();
  /**
   * <code>string refresh_token = 2;</code>
   * @return The bytes for refreshToken.
   */
  com.google.protobuf.ByteString
      getRefreshTokenBytes();

  /**
   * <code>string token_type = 3;</code>
   * @return The tokenType.
   */
  java.lang.String getTokenType();
  /**
   * <code>string token_type = 3;</code>
   * @return The bytes for tokenType.
   */
  com.google.protobuf.ByteString
      getTokenTypeBytes();

  /**
   * <code>int64 expires_in = 4;</code>
   * @return The expiresIn.
   */
  long getExpiresIn();
}
