// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.34.2

package com.example.grpc.auth;

@com.google.protobuf.Generated
public interface ValidateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.auth.ValidateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool valid = 1;</code>
   * @return The valid.
   */
  boolean getValid();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>repeated string authorities = 3;</code>
   * @return A list containing the authorities.
   */
  java.util.List<java.lang.String>
      getAuthoritiesList();
  /**
   * <code>repeated string authorities = 3;</code>
   * @return The count of authorities.
   */
  int getAuthoritiesCount();
  /**
   * <code>repeated string authorities = 3;</code>
   * @param index The index of the element to return.
   * @return The authorities at the given index.
   */
  java.lang.String getAuthorities(int index);
  /**
   * <code>repeated string authorities = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the authorities at the given index.
   */
  com.google.protobuf.ByteString
      getAuthoritiesBytes(int index);

  /**
   * <code>int64 userId = 4;</code>
   * @return The userId.
   */
  long getUserId();
}
