// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: book.proto
// Protobuf Java Version: 4.34.2

package com.example.bookapp.proto;

@com.google.protobuf.Generated
public final class BookProto extends com.google.protobuf.GeneratedFile {
  private BookProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 2,
      /* suffix= */ "",
      "BookProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_bookapp_proto_BookId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_bookapp_proto_BookId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_bookapp_proto_Book_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_bookapp_proto_Book_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbook.proto\022\031com.example.bookapp.proto\"" +
      "\024\n\006BookId\022\n\n\002id\030\001 \001(\t\"?\n\004Book\022\n\n\002id\030\001 \001(" +
      "\t\022\r\n\005title\030\002 \001(\t\022\016\n\006author\030\003 \001(\t\022\014\n\004year" +
      "\030\004 \001(\0052^\n\013BookService\022O\n\007GetBook\022!.com.e" +
      "xample.bookapp.proto.BookId\032\037.com.exampl" +
      "e.bookapp.proto.Book\"\000B*\n\031com.example.bo" +
      "okapp.protoB\tBookProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_bookapp_proto_BookId_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_example_bookapp_proto_BookId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_bookapp_proto_BookId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_bookapp_proto_Book_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_com_example_bookapp_proto_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_bookapp_proto_Book_descriptor,
        new java.lang.String[] { "Id", "Title", "Author", "Year", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
