// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: book.proto
// Protobuf Java Version: 4.34.2

package com.example.bookapp.proto;

@com.google.protobuf.Generated
public interface BookIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.bookapp.proto.BookId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
