// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.34.2

package com.example.grpc.auth;

@com.google.protobuf.Generated
public final class Auth extends com.google.protobuf.GeneratedFile {
  private Auth() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 2,
      /* suffix= */ "",
      "Auth");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_auth_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_auth_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_auth_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_auth_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_auth_RefreshRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_auth_RefreshRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_auth_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_auth_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_auth_ValidateTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_auth_ValidateTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_auth_AuthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_auth_AuthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_auth_ValidateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_auth_ValidateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_auth_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_auth_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\022\025com.example.grpc.auth\"2\n\014L" +
      "oginRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010passwor" +
      "d\030\002 \001(\t\"U\n\017RegisterRequest\022\020\n\010username\030\001" +
      " \001(\t\022\r\n\005email\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\017\n" +
      "\007user_id\030\004 \001(\t\"\'\n\016RefreshRequest\022\025\n\rrefr" +
      "esh_token\030\001 \001(\t\"&\n\rLogoutRequest\022\025\n\rrefr" +
      "esh_token\030\001 \001(\t\"%\n\024ValidateTokenRequest\022" +
      "\r\n\005token\030\001 \001(\t\"c\n\014AuthResponse\022\024\n\014access" +
      "_token\030\001 \001(\t\022\025\n\rrefresh_token\030\002 \001(\t\022\022\n\nt" +
      "oken_type\030\003 \001(\t\022\022\n\nexpires_in\030\004 \001(\003\"3\n\020V" +
      "alidateResponse\022\r\n\005valid\030\001 \001(\010\022\020\n\010userna" +
      "me\030\002 \001(\t\"\007\n\005Empty2\300\003\n\013AuthService\022Q\n\005Log" +
      "in\022#.com.example.grpc.auth.LoginRequest\032" +
      "#.com.example.grpc.auth.AuthResponse\022W\n\010" +
      "Register\022&.com.example.grpc.auth.Registe" +
      "rRequest\032#.com.example.grpc.auth.AuthRes" +
      "ponse\022U\n\007Refresh\022%.com.example.grpc.auth" +
      ".RefreshRequest\032#.com.example.grpc.auth." +
      "AuthResponse\022L\n\006Logout\022$.com.example.grp" +
      "c.auth.LogoutRequest\032\034.com.example.grpc." +
      "auth.Empty\022`\n\010Validate\022+.com.example.grp" +
      "c.auth.ValidateTokenRequest\032\'.com.exampl" +
      "e.grpc.auth.ValidateResponseB\031\n\025com.exam" +
      "ple.grpc.authP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_grpc_auth_LoginRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_example_grpc_auth_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_auth_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_com_example_grpc_auth_RegisterRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_com_example_grpc_auth_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_auth_RegisterRequest_descriptor,
        new java.lang.String[] { "Username", "Email", "Password", "UserId", });
    internal_static_com_example_grpc_auth_RefreshRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_com_example_grpc_auth_RefreshRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_auth_RefreshRequest_descriptor,
        new java.lang.String[] { "RefreshToken", });
    internal_static_com_example_grpc_auth_LogoutRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_com_example_grpc_auth_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_auth_LogoutRequest_descriptor,
        new java.lang.String[] { "RefreshToken", });
    internal_static_com_example_grpc_auth_ValidateTokenRequest_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_com_example_grpc_auth_ValidateTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_auth_ValidateTokenRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_com_example_grpc_auth_AuthResponse_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_com_example_grpc_auth_AuthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_auth_AuthResponse_descriptor,
        new java.lang.String[] { "AccessToken", "RefreshToken", "TokenType", "ExpiresIn", });
    internal_static_com_example_grpc_auth_ValidateResponse_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_com_example_grpc_auth_ValidateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_auth_ValidateResponse_descriptor,
        new java.lang.String[] { "Valid", "Username", });
    internal_static_com_example_grpc_auth_Empty_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_com_example_grpc_auth_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_auth_Empty_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
