// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.34.2

package com.example.grpc.auth;

@com.google.protobuf.Generated
public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.auth.LogoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string refresh_token = 1;</code>
   * @return The refreshToken.
   */
  java.lang.String getRefreshToken();
  /**
   * <code>string refresh_token = 1;</code>
   * @return The bytes for refreshToken.
   */
  com.google.protobuf.ByteString
      getRefreshTokenBytes();
}
