// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.34.2

package com.example.grpc.auth;

@com.google.protobuf.Generated
public interface ValidateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.auth.ValidateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool valid = 1;</code>
   * @return The valid.
   */
  boolean getValid();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
