apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
spec:
  selector:
    app: postgres-auth
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-auth
spec:
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_DB
          value: "authentication_db"
        - name: POSTGRES_USER
          value: "authuser"
        - name: POSTGRES_PASSWORD
          value: "authpass"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        emptyDir: {}
