// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.34.2

package com.example.grpc.user;

@com.google.protobuf.Generated
public interface GetUserByIdentityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.user.GetUserByIdentityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
