// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.34.2

package com.example.grpc.user;

@com.google.protobuf.Generated
public interface GetUserByUsernameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.user.GetUserByUsernameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
