// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.34.2

package com.example.grpc.user;

@com.google.protobuf.Generated
public final class User extends com.google.protobuf.GeneratedFile {
  private User() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 2,
      /* suffix= */ "",
      "User");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_user_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_user_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_user_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_user_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_user_GetUserByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_user_GetUserByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_user_GetUserByUsernameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_user_GetUserByUsernameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_user_GetUserByIdentityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_user_GetUserByIdentityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_user_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_grpc_user_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\025com.example.grpc.user\"H\n\017R" +
      "egisterRequest\022\020\n\010username\030\001 \001(\t\022\r\n\005emai" +
      "l\030\002 \001(\t\022\024\n\014display_name\030\004 \001(\t\"L\n\014UserRes" +
      "ponse\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005email" +
      "\030\003 \001(\t\022\023\n\013displayName\030\004 \001(\t\" \n\022GetUserBy" +
      "IdRequest\022\n\n\002id\030\001 \001(\005\",\n\030GetUserByUserna" +
      "meRequest\022\020\n\010username\030\001 \001(\t\"*\n\030GetUserBy" +
      "IdentityRequest\022\016\n\006userId\030\001 \001(\t\"\007\n\005Empty" +
      "2\233\003\n\013UserService\022W\n\010Register\022&.com.examp" +
      "le.grpc.user.RegisterRequest\032#.com.examp" +
      "le.grpc.user.UserResponse\022]\n\013GetUserById" +
      "\022).com.example.grpc.user.GetUserByIdRequ" +
      "est\032#.com.example.grpc.user.UserResponse" +
      "\022i\n\021GetUserByUsername\022/.com.example.grpc" +
      ".user.GetUserByUsernameRequest\032#.com.exa" +
      "mple.grpc.user.UserResponse\022i\n\021GetUserBy" +
      "Identity\022/.com.example.grpc.user.GetUser" +
      "ByIdentityRequest\032#.com.example.grpc.use" +
      "r.UserResponseB\031\n\025com.example.grpc.userP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_grpc_user_RegisterRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_example_grpc_user_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_user_RegisterRequest_descriptor,
        new java.lang.String[] { "Username", "Email", "DisplayName", });
    internal_static_com_example_grpc_user_UserResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_com_example_grpc_user_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_user_UserResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "DisplayName", });
    internal_static_com_example_grpc_user_GetUserByIdRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_com_example_grpc_user_GetUserByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_user_GetUserByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_grpc_user_GetUserByUsernameRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_com_example_grpc_user_GetUserByUsernameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_user_GetUserByUsernameRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_example_grpc_user_GetUserByIdentityRequest_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_com_example_grpc_user_GetUserByIdentityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_user_GetUserByIdentityRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_example_grpc_user_Empty_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_com_example_grpc_user_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_grpc_user_Empty_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
